---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "swagger definition for org.apache.servicecomb.toolkit.hello.HelloController"
  x-java-interface: "gen.swagger.HelloControllerIntf"
basePath: "/"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /hello/{name}:
    get:
      operationId: "sayHello"
      parameters:
      - name: "name"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "response of 200"
          schema:
            type: "string"
